---
- hosts: all
  vars:
     password: $6$rounds=656000$Urn34tXXRHTpX7cb$XE0pWQehiaNsjnLBM2wJjPO9atvBKcDuzR42ojFeDdqXOAxnQD.oNd0GgeoEOSnm05n3sgvwGAagJWj5GQkEu.
  tasks:
     - name: change password
       user:
          name: "zabbix"
          update_password: always
          password: "{{password}}"
