---
- hosts: all
  tasks:
    - name: copy shannon driver file
      copy:
         src: "{{ item.src }}"
         dest: "{{ item.dest }}"
         owner: root
         group: root
         mode: 0644
      with_items:
         - {
            src: "/software_files/shannon/shannon-module-3.10.0-862.3.2.el7.x86_64-3.1-3.x86_64.rpm",
            dest: "/root/shannon-module-3.10.0-862.3.2.el7.x86_64-3.1-3.x86_64.rpm" } 
    - name: copy shannon util file
      copy:
         src: "{{ item.src }}"
         dest: "{{ item.dest }}"
         owner: root
         group: root
         mode: 0644
      with_items:
         - {
            src: "/software_files/shannon/shannon-utils-3.1-2.x86_64.rpm",
            dest: "/root/shannon-utils-3.1-2.x86_64.rpm" } 
