---
- hosts: rdma 
  tasks:
    - name: copy repo to remote
      copy: 
        src: /etc/yum.repos.d/internal.repo
        dest: /etc/yum.repos.d/internal.repo
    - name: copy docker scripts to remote
      copy:
        src: /root/go/src/github.com/majorinche/ansible_scripts/okd_cluster_install/pull_okd_images.sh
        dest: /root/pull_okd_images.sh
        mode: 0500
    - name: copy ssl to remote
      copy:
        src: /root/go/src/github.com/majorinche/ansible_scripts/okd_cluster_install/ssl_config.sh
        dest: /root/ssl_config.sh
        mode: 0500
    - name: find CentOS repo files
      find: 
        paths: /etc/yum.repos.d
        patterns: CentOS*.repo
      register: wait_to_delete
    - name: delete CentOS repo files
      file:
        path: "{{ item.path }}"
        state: absent
      with_items: "{{ wait_to_delete.files }}"
